; Generated by tools\gen_rom_components.py - do not edit by hand.
;
; One component per (phone, language) pair, and the package files that
; pair owns. A language whose text-to-phoneme and prosody packages are
; not laid down is not a candidate language when the engine scans the
; data tree, so its voices never reach the voice list.
;
; The voice banks (srsf kind 2) are deliberately NOT split by language:
; the engine asks for a bank by an id that is not always the language
; being spoken, because builds share banks between languages. They come
; to well under a megabyte per phone, so they all come along with the
; phone and only the per-language packages are selectable.
;
; The phone components are here too, each one directly above the entries
; that belong to it. The wizard nests its components list by adjacency
; and depth rather than by name, so a phone and its languages have to be
; kept together: split them up and the languages become children of
; whichever phone happens to be listed last.

[Components]

; ---- Nokia 5320 ----
Name: "roms\p5320"; Description: "Nokia 5320 - 33 languages, male and female (69 MB)"; Types: compact custom english full
Name: "roms\p5320\male"; Description: "Male voices"; Types: compact custom english full
Name: "roms\p5320\female"; Description: "Female voices"; Types: custom english full

Name: "roms\p5320\l1"; Description: "English (UK)"; Types: compact custom english full
Name: "roms\p5320\l2"; Description: "French"; Types: custom full
Name: "roms\p5320\l3"; Description: "German"; Types: custom full
Name: "roms\p5320\l4"; Description: "Spanish"; Types: custom full
Name: "roms\p5320\l5"; Description: "Italian"; Types: custom full
Name: "roms\p5320\l6"; Description: "Swedish"; Types: custom full
Name: "roms\p5320\l7"; Description: "Danish"; Types: custom full
Name: "roms\p5320\l8"; Description: "Norwegian"; Types: custom full
Name: "roms\p5320\l9"; Description: "Finnish"; Types: custom full
Name: "roms\p5320\l13"; Description: "Portuguese"; Types: custom full
Name: "roms\p5320\l14"; Description: "Turkish"; Types: custom full
Name: "roms\p5320\l15"; Description: "Icelandic"; Types: custom full
Name: "roms\p5320\l16"; Description: "Russian"; Types: custom full
Name: "roms\p5320\l17"; Description: "Hungarian"; Types: custom full
Name: "roms\p5320\l18"; Description: "Dutch"; Types: custom full
Name: "roms\p5320\l25"; Description: "Czech"; Types: custom full
Name: "roms\p5320\l26"; Description: "Slovak"; Types: custom full
Name: "roms\p5320\l27"; Description: "Polish"; Types: custom full
Name: "roms\p5320\l28"; Description: "Slovenian"; Types: custom full
Name: "roms\p5320\l37"; Description: "Arabic"; Types: custom full
Name: "roms\p5320\l42"; Description: "Bulgarian"; Types: custom full
Name: "roms\p5320\l44"; Description: "Catalan"; Types: custom full
Name: "roms\p5320\l45"; Description: "Croatian"; Types: custom full
Name: "roms\p5320\l49"; Description: "Estonian"; Types: custom full
Name: "roms\p5320\l54"; Description: "Greek"; Types: custom full
Name: "roms\p5320\l57"; Description: "Hebrew"; Types: custom full
Name: "roms\p5320\l67"; Description: "Latvian"; Types: custom full
Name: "roms\p5320\l68"; Description: "Lithuanian"; Types: custom full
Name: "roms\p5320\l78"; Description: "Romanian"; Types: custom full
Name: "roms\p5320\l79"; Description: "Serbian"; Types: custom full
Name: "roms\p5320\l93"; Description: "Ukrainian"; Types: custom full
Name: "roms\p5320\l401"; Description: "Basque"; Types: custom full
Name: "roms\p5320\l402"; Description: "Galician"; Types: custom full

; ---- Nokia E65 ----
Name: "roms\pe65"; Description: "Nokia E65 - 30 languages (19 MB)"; Types: custom english full

Name: "roms\pe65\l1"; Description: "English (UK)"; Types: custom english full
Name: "roms\pe65\l2"; Description: "French"; Types: custom full
Name: "roms\pe65\l3"; Description: "German"; Types: custom full
Name: "roms\pe65\l4"; Description: "Spanish"; Types: custom full
Name: "roms\pe65\l5"; Description: "Italian"; Types: custom full
Name: "roms\pe65\l6"; Description: "Swedish"; Types: custom full
Name: "roms\pe65\l7"; Description: "Danish"; Types: custom full
Name: "roms\pe65\l8"; Description: "Norwegian"; Types: custom full
Name: "roms\pe65\l9"; Description: "Finnish"; Types: custom full
Name: "roms\pe65\l13"; Description: "Portuguese"; Types: custom full
Name: "roms\pe65\l14"; Description: "Turkish"; Types: custom full
Name: "roms\pe65\l15"; Description: "Icelandic"; Types: custom full
Name: "roms\pe65\l16"; Description: "Russian"; Types: custom full
Name: "roms\pe65\l17"; Description: "Hungarian"; Types: custom full
Name: "roms\pe65\l18"; Description: "Dutch"; Types: custom full
Name: "roms\pe65\l25"; Description: "Czech"; Types: custom full
Name: "roms\pe65\l26"; Description: "Slovak"; Types: custom full
Name: "roms\pe65\l27"; Description: "Polish"; Types: custom full
Name: "roms\pe65\l28"; Description: "Slovenian"; Types: custom full
Name: "roms\pe65\l37"; Description: "Arabic"; Types: custom full
Name: "roms\pe65\l42"; Description: "Bulgarian"; Types: custom full
Name: "roms\pe65\l45"; Description: "Croatian"; Types: custom full
Name: "roms\pe65\l49"; Description: "Estonian"; Types: custom full
Name: "roms\pe65\l54"; Description: "Greek"; Types: custom full
Name: "roms\pe65\l57"; Description: "Hebrew"; Types: custom full
Name: "roms\pe65\l67"; Description: "Latvian"; Types: custom full
Name: "roms\pe65\l68"; Description: "Lithuanian"; Types: custom full
Name: "roms\pe65\l78"; Description: "Romanian"; Types: custom full
Name: "roms\pe65\l79"; Description: "Serbian"; Types: custom full
Name: "roms\pe65\l93"; Description: "Ukrainian"; Types: custom full

; ---- Nokia N95 8GB ----
Name: "roms\pn958gb"; Description: "Nokia N95 8GB - 30 languages (58 MB)"; Types: custom english full

Name: "roms\pn958gb\l1"; Description: "English (UK)"; Types: custom english full
Name: "roms\pn958gb\l2"; Description: "French"; Types: custom full
Name: "roms\pn958gb\l3"; Description: "German"; Types: custom full
Name: "roms\pn958gb\l4"; Description: "Spanish"; Types: custom full
Name: "roms\pn958gb\l5"; Description: "Italian"; Types: custom full
Name: "roms\pn958gb\l6"; Description: "Swedish"; Types: custom full
Name: "roms\pn958gb\l7"; Description: "Danish"; Types: custom full
Name: "roms\pn958gb\l8"; Description: "Norwegian"; Types: custom full
Name: "roms\pn958gb\l9"; Description: "Finnish"; Types: custom full
Name: "roms\pn958gb\l13"; Description: "Portuguese"; Types: custom full
Name: "roms\pn958gb\l14"; Description: "Turkish"; Types: custom full
Name: "roms\pn958gb\l15"; Description: "Icelandic"; Types: custom full
Name: "roms\pn958gb\l16"; Description: "Russian"; Types: custom full
Name: "roms\pn958gb\l17"; Description: "Hungarian"; Types: custom full
Name: "roms\pn958gb\l18"; Description: "Dutch"; Types: custom full
Name: "roms\pn958gb\l25"; Description: "Czech"; Types: custom full
Name: "roms\pn958gb\l26"; Description: "Slovak"; Types: custom full
Name: "roms\pn958gb\l27"; Description: "Polish"; Types: custom full
Name: "roms\pn958gb\l28"; Description: "Slovenian"; Types: custom full
Name: "roms\pn958gb\l37"; Description: "Arabic"; Types: custom full
Name: "roms\pn958gb\l42"; Description: "Bulgarian"; Types: custom full
Name: "roms\pn958gb\l45"; Description: "Croatian"; Types: custom full
Name: "roms\pn958gb\l49"; Description: "Estonian"; Types: custom full
Name: "roms\pn958gb\l54"; Description: "Greek"; Types: custom full
Name: "roms\pn958gb\l57"; Description: "Hebrew"; Types: custom full
Name: "roms\pn958gb\l67"; Description: "Latvian"; Types: custom full
Name: "roms\pn958gb\l68"; Description: "Lithuanian"; Types: custom full
Name: "roms\pn958gb\l78"; Description: "Romanian"; Types: custom full
Name: "roms\pn958gb\l79"; Description: "Serbian"; Types: custom full
Name: "roms\pn958gb\l93"; Description: "Ukrainian"; Types: custom full

; ---- Nokia 6650 ----
Name: "roms\p6650"; Description: "Nokia 6650 - English (US), French (Canada), Portuguese (Brazil) and Spanish (Latin America) (45 MB)"; Types: custom english full
Name: "roms\p6650\male"; Description: "Male voices"; Types: custom english full
Name: "roms\p6650\female"; Description: "Female voices"; Types: custom english full

Name: "roms\p6650\l10"; Description: "English (US)"; Types: custom english full
Name: "roms\p6650\l51"; Description: "French (Canada)"; Types: custom full
Name: "roms\p6650\l76"; Description: "Portuguese (Brazil)"; Types: custom full
Name: "roms\p6650\l83"; Description: "Spanish (Latin America)"; Types: custom full

; ---- Nokia N85 ----
Name: "roms\pn85"; Description: "Nokia N85 - Tagalog and Vietnamese (42 MB)"; Types: custom full
Name: "roms\pn85\male"; Description: "Male voices"; Types: custom full
Name: "roms\pn85\female"; Description: "Female voices"; Types: custom full

Name: "roms\pn85\l39"; Description: "Tagalog"; Types: custom full
Name: "roms\pn85\l96"; Description: "Vietnamese"; Types: custom full

[Files]

; ---- Nokia 5320 ----
Source: "{#RomRoot}\5320\files\system\data\srsf_0_1.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l1
Source: "{#RomRoot}\5320\files\system\data\srsf_4_1.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l1
Source: "{#RomRoot}\5320\files\system\data\srsf_0_2.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l2
Source: "{#RomRoot}\5320\files\system\data\srsf_4_2.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l2
Source: "{#RomRoot}\5320\files\system\data\srsf_0_3.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l3
Source: "{#RomRoot}\5320\files\system\data\srsf_4_3.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l3
Source: "{#RomRoot}\5320\files\system\data\srsf_0_4.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l4
Source: "{#RomRoot}\5320\files\system\data\srsf_4_4.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l4
Source: "{#RomRoot}\5320\files\system\data\srsf_0_5.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l5
Source: "{#RomRoot}\5320\files\system\data\srsf_4_5.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l5
Source: "{#RomRoot}\5320\files\system\data\srsf_0_6.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l6
Source: "{#RomRoot}\5320\files\system\data\srsf_4_6.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l6
Source: "{#RomRoot}\5320\files\system\data\srsf_0_7.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l7
Source: "{#RomRoot}\5320\files\system\data\srsf_4_7.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l7
Source: "{#RomRoot}\5320\files\system\data\srsf_0_8.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l8
Source: "{#RomRoot}\5320\files\system\data\srsf_4_8.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l8
Source: "{#RomRoot}\5320\files\system\data\srsf_0_9.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l9
Source: "{#RomRoot}\5320\files\system\data\srsf_4_9.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l9
Source: "{#RomRoot}\5320\files\system\data\srsf_0_13.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l13
Source: "{#RomRoot}\5320\files\system\data\srsf_4_13.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l13
Source: "{#RomRoot}\5320\files\system\data\srsf_0_14.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l14
Source: "{#RomRoot}\5320\files\system\data\srsf_4_14.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l14
Source: "{#RomRoot}\5320\files\system\data\srsf_0_15.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l15
Source: "{#RomRoot}\5320\files\system\data\srsf_4_15.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l15
Source: "{#RomRoot}\5320\files\system\data\srsf_0_16.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l16
Source: "{#RomRoot}\5320\files\system\data\srsf_4_16.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l16
Source: "{#RomRoot}\5320\files\system\data\srsf_0_17.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l17
Source: "{#RomRoot}\5320\files\system\data\srsf_4_17.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l17
Source: "{#RomRoot}\5320\files\system\data\srsf_0_18.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l18
Source: "{#RomRoot}\5320\files\system\data\srsf_4_18.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l18
Source: "{#RomRoot}\5320\files\system\data\srsf_0_25.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l25
Source: "{#RomRoot}\5320\files\system\data\srsf_4_25.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l25
Source: "{#RomRoot}\5320\files\system\data\srsf_0_26.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l26
Source: "{#RomRoot}\5320\files\system\data\srsf_4_26.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l26
Source: "{#RomRoot}\5320\files\system\data\srsf_0_27.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l27
Source: "{#RomRoot}\5320\files\system\data\srsf_4_27.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l27
Source: "{#RomRoot}\5320\files\system\data\srsf_0_28.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l28
Source: "{#RomRoot}\5320\files\system\data\srsf_4_28.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l28
Source: "{#RomRoot}\5320\files\system\data\srsf_0_37.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l37
Source: "{#RomRoot}\5320\files\system\data\srsf_4_37.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l37
Source: "{#RomRoot}\5320\files\system\data\srsf_0_42.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l42
Source: "{#RomRoot}\5320\files\system\data\srsf_4_42.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l42
Source: "{#RomRoot}\5320\files\system\data\srsf_0_44.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l44
Source: "{#RomRoot}\5320\files\system\data\srsf_4_44.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l44
Source: "{#RomRoot}\5320\files\system\data\srsf_0_45.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l45
Source: "{#RomRoot}\5320\files\system\data\srsf_4_45.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l45
Source: "{#RomRoot}\5320\files\system\data\srsf_0_49.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l49
Source: "{#RomRoot}\5320\files\system\data\srsf_4_49.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l49
Source: "{#RomRoot}\5320\files\system\data\srsf_0_54.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l54
Source: "{#RomRoot}\5320\files\system\data\srsf_4_54.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l54
Source: "{#RomRoot}\5320\files\system\data\srsf_0_57.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l57
Source: "{#RomRoot}\5320\files\system\data\srsf_4_57.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l57
Source: "{#RomRoot}\5320\files\system\data\srsf_0_67.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l67
Source: "{#RomRoot}\5320\files\system\data\srsf_4_67.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l67
Source: "{#RomRoot}\5320\files\system\data\srsf_0_68.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l68
Source: "{#RomRoot}\5320\files\system\data\srsf_4_68.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l68
Source: "{#RomRoot}\5320\files\system\data\srsf_0_78.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l78
Source: "{#RomRoot}\5320\files\system\data\srsf_4_78.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l78
Source: "{#RomRoot}\5320\files\system\data\srsf_0_79.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l79
Source: "{#RomRoot}\5320\files\system\data\srsf_4_79.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l79
Source: "{#RomRoot}\5320\files\system\data\srsf_0_93.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l93
Source: "{#RomRoot}\5320\files\system\data\srsf_4_93.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l93
Source: "{#RomRoot}\5320\files\system\data\srsf_0_401.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l401
Source: "{#RomRoot}\5320\files\system\data\srsf_4_401.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l401
Source: "{#RomRoot}\5320\files\system\data\srsf_0_402.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l402
Source: "{#RomRoot}\5320\files\system\data\srsf_4_402.bin"; DestDir: "{app}\roms\5320\files\system\data"; Flags: ignoreversion; Components: roms\p5320\l402

; ---- Nokia E65 ----
Source: "{#RomRoot}\e65\files\system\data\srsf_0_1.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l1
Source: "{#RomRoot}\e65\files\system\data\srsf_0_2.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l2
Source: "{#RomRoot}\e65\files\system\data\srsf_0_3.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l3
Source: "{#RomRoot}\e65\files\system\data\srsf_0_4.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l4
Source: "{#RomRoot}\e65\files\system\data\srsf_0_5.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l5
Source: "{#RomRoot}\e65\files\system\data\srsf_0_6.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l6
Source: "{#RomRoot}\e65\files\system\data\srsf_0_7.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l7
Source: "{#RomRoot}\e65\files\system\data\srsf_0_8.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l8
Source: "{#RomRoot}\e65\files\system\data\srsf_0_9.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l9
Source: "{#RomRoot}\e65\files\system\data\srsf_0_13.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l13
Source: "{#RomRoot}\e65\files\system\data\srsf_0_14.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l14
Source: "{#RomRoot}\e65\files\system\data\srsf_0_15.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l15
Source: "{#RomRoot}\e65\files\system\data\srsf_0_16.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l16
Source: "{#RomRoot}\e65\files\system\data\srsf_0_17.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l17
Source: "{#RomRoot}\e65\files\system\data\srsf_0_18.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l18
Source: "{#RomRoot}\e65\files\system\data\srsf_0_25.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l25
Source: "{#RomRoot}\e65\files\system\data\srsf_0_26.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l26
Source: "{#RomRoot}\e65\files\system\data\srsf_0_27.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l27
Source: "{#RomRoot}\e65\files\system\data\srsf_0_28.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l28
Source: "{#RomRoot}\e65\files\system\data\srsf_0_37.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l37
Source: "{#RomRoot}\e65\files\system\data\srsf_0_42.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l42
Source: "{#RomRoot}\e65\files\system\data\srsf_0_45.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l45
Source: "{#RomRoot}\e65\files\system\data\srsf_0_49.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l49
Source: "{#RomRoot}\e65\files\system\data\srsf_0_54.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l54
Source: "{#RomRoot}\e65\files\system\data\srsf_0_57.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l57
Source: "{#RomRoot}\e65\files\system\data\srsf_0_67.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l67
Source: "{#RomRoot}\e65\files\system\data\srsf_0_68.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l68
Source: "{#RomRoot}\e65\files\system\data\srsf_0_78.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l78
Source: "{#RomRoot}\e65\files\system\data\srsf_0_79.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l79
Source: "{#RomRoot}\e65\files\system\data\srsf_0_93.bin"; DestDir: "{app}\roms\e65\files\system\data"; Flags: ignoreversion; Components: roms\pe65\l93

; ---- Nokia N95 8GB ----
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_1.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l1
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_2.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l2
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_3.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l3
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_4.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l4
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_5.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l5
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_6.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l6
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_7.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l7
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_8.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l8
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_9.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l9
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_13.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l13
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_14.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l14
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_15.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l15
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_16.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l16
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_17.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l17
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_18.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l18
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_25.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l25
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_26.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l26
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_27.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l27
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_28.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l28
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_37.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l37
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_42.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l42
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_45.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l45
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_49.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l49
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_54.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l54
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_57.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l57
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_67.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l67
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_68.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l68
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_78.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l78
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_79.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l79
Source: "{#RomRoot}\n958gb\files\system\data\srsf_0_93.bin"; DestDir: "{app}\roms\n958gb\files\system\data"; Flags: ignoreversion; Components: roms\pn958gb\l93

; ---- Nokia 6650 ----
Source: "{#RomRoot}\6650\files\system\data\srsf_0_10.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l10
Source: "{#RomRoot}\6650\files\system\data\srsf_4_10.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l10
Source: "{#RomRoot}\6650\files\system\data\srsf_0_51.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l51
Source: "{#RomRoot}\6650\files\system\data\srsf_4_51.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l51
Source: "{#RomRoot}\6650\files\system\data\srsf_0_76.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l76
Source: "{#RomRoot}\6650\files\system\data\srsf_4_76.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l76
Source: "{#RomRoot}\6650\files\system\data\srsf_0_83.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l83
Source: "{#RomRoot}\6650\files\system\data\srsf_4_83.bin"; DestDir: "{app}\roms\6650\files\system\data"; Flags: ignoreversion; Components: roms\p6650\l83

; ---- Nokia N85 ----
Source: "{#RomRoot}\n85\files\system\data\srsf_0_39.bin"; DestDir: "{app}\roms\n85\files\system\data"; Flags: ignoreversion; Components: roms\pn85\l39
Source: "{#RomRoot}\n85\files\system\data\srsf_4_39.bin"; DestDir: "{app}\roms\n85\files\system\data"; Flags: ignoreversion; Components: roms\pn85\l39
Source: "{#RomRoot}\n85\files\system\data\srsf_0_96.bin"; DestDir: "{app}\roms\n85\files\system\data"; Flags: ignoreversion; Components: roms\pn85\l96
Source: "{#RomRoot}\n85\files\system\data\srsf_4_96.bin"; DestDir: "{app}\roms\n85\files\system\data"; Flags: ignoreversion; Components: roms\pn85\l96
